// AUTO-GENERATED by scripts/economic_calendar_contract.py. DO NOT EDIT BY HAND.
#property strict

const bool GTX_ECONOMIC_CALENDAR_APPROVED = false;
const string GTX_ECONOMIC_CALENDAR_ID = "GTX-ECONOMIC-CALENDAR-2021-2025-V1";
const string GTX_ECONOMIC_CALENDAR_SHA256 = "6263fb75285b8aeb24c157e9fb8eeb09a15de30c682ceb69479177edf38954bd";
const string GTX_ECONOMIC_CALENDAR_START_UTC = "2021-01-01T00:00:00Z";
const string GTX_ECONOMIC_CALENDAR_END_UTC = "2025-12-31T23:59:59Z";

bool GTX_IsExactNfpReleaseDate(int year, int mon, int day)
  {
   return((year==2021 && mon==1 && day==8) ||
          (year==2021 && mon==2 && day==5) ||
          (year==2021 && mon==3 && day==5) ||
          (year==2021 && mon==4 && day==2) ||
          (year==2021 && mon==5 && day==7) ||
          (year==2021 && mon==6 && day==4) ||
          (year==2021 && mon==7 && day==2) ||
          (year==2021 && mon==8 && day==6) ||
          (year==2021 && mon==9 && day==3) ||
          (year==2021 && mon==10 && day==8) ||
          (year==2021 && mon==11 && day==5) ||
          (year==2021 && mon==12 && day==3) ||
          (year==2022 && mon==1 && day==7) ||
          (year==2022 && mon==2 && day==4) ||
          (year==2022 && mon==3 && day==4) ||
          (year==2022 && mon==4 && day==1) ||
          (year==2022 && mon==5 && day==6) ||
          (year==2022 && mon==6 && day==3) ||
          (year==2022 && mon==7 && day==8) ||
          (year==2022 && mon==8 && day==5) ||
          (year==2022 && mon==9 && day==2) ||
          (year==2022 && mon==10 && day==7) ||
          (year==2022 && mon==11 && day==4) ||
          (year==2022 && mon==12 && day==2) ||
          (year==2023 && mon==1 && day==6) ||
          (year==2023 && mon==2 && day==3) ||
          (year==2023 && mon==3 && day==10) ||
          (year==2023 && mon==4 && day==7) ||
          (year==2023 && mon==5 && day==5) ||
          (year==2023 && mon==6 && day==2) ||
          (year==2023 && mon==7 && day==7) ||
          (year==2023 && mon==8 && day==4) ||
          (year==2023 && mon==9 && day==1) ||
          (year==2023 && mon==10 && day==6) ||
          (year==2023 && mon==11 && day==3) ||
          (year==2023 && mon==12 && day==8) ||
          (year==2024 && mon==1 && day==5) ||
          (year==2024 && mon==2 && day==2) ||
          (year==2024 && mon==3 && day==8) ||
          (year==2024 && mon==4 && day==5) ||
          (year==2024 && mon==5 && day==3) ||
          (year==2024 && mon==6 && day==7) ||
          (year==2024 && mon==7 && day==5) ||
          (year==2024 && mon==8 && day==2) ||
          (year==2024 && mon==9 && day==6) ||
          (year==2024 && mon==10 && day==4) ||
          (year==2024 && mon==11 && day==1) ||
          (year==2024 && mon==12 && day==6) ||
          (year==2025 && mon==1 && day==10) ||
          (year==2025 && mon==2 && day==7) ||
          (year==2025 && mon==3 && day==7) ||
          (year==2025 && mon==4 && day==4) ||
          (year==2025 && mon==5 && day==2) ||
          (year==2025 && mon==6 && day==6) ||
          (year==2025 && mon==7 && day==3) ||
          (year==2025 && mon==8 && day==1) ||
          (year==2025 && mon==9 && day==5) ||
          (year==2025 && mon==11 && day==20) ||
          (year==2025 && mon==12 && day==16));
  }

bool GTX_IsExactCpiReleaseDate(int year, int mon, int day)
  {
   return((year==2021 && mon==1 && day==13) ||
          (year==2021 && mon==2 && day==10) ||
          (year==2021 && mon==3 && day==10) ||
          (year==2021 && mon==4 && day==13) ||
          (year==2021 && mon==5 && day==12) ||
          (year==2021 && mon==6 && day==10) ||
          (year==2021 && mon==7 && day==13) ||
          (year==2021 && mon==8 && day==11) ||
          (year==2021 && mon==9 && day==14) ||
          (year==2021 && mon==10 && day==13) ||
          (year==2021 && mon==11 && day==10) ||
          (year==2021 && mon==12 && day==10) ||
          (year==2022 && mon==1 && day==12) ||
          (year==2022 && mon==2 && day==10) ||
          (year==2022 && mon==3 && day==10) ||
          (year==2022 && mon==4 && day==12) ||
          (year==2022 && mon==5 && day==11) ||
          (year==2022 && mon==6 && day==10) ||
          (year==2022 && mon==7 && day==13) ||
          (year==2022 && mon==8 && day==10) ||
          (year==2022 && mon==9 && day==13) ||
          (year==2022 && mon==10 && day==13) ||
          (year==2022 && mon==11 && day==10) ||
          (year==2022 && mon==12 && day==13) ||
          (year==2023 && mon==1 && day==12) ||
          (year==2023 && mon==2 && day==14) ||
          (year==2023 && mon==3 && day==14) ||
          (year==2023 && mon==4 && day==12) ||
          (year==2023 && mon==5 && day==10) ||
          (year==2023 && mon==6 && day==13) ||
          (year==2023 && mon==7 && day==12) ||
          (year==2023 && mon==8 && day==10) ||
          (year==2023 && mon==9 && day==13) ||
          (year==2023 && mon==10 && day==12) ||
          (year==2023 && mon==11 && day==14) ||
          (year==2023 && mon==12 && day==12) ||
          (year==2024 && mon==1 && day==11) ||
          (year==2024 && mon==2 && day==13) ||
          (year==2024 && mon==3 && day==12) ||
          (year==2024 && mon==4 && day==10) ||
          (year==2024 && mon==5 && day==15) ||
          (year==2024 && mon==6 && day==12) ||
          (year==2024 && mon==7 && day==11) ||
          (year==2024 && mon==8 && day==14) ||
          (year==2024 && mon==9 && day==11) ||
          (year==2024 && mon==10 && day==10) ||
          (year==2024 && mon==11 && day==13) ||
          (year==2024 && mon==12 && day==11) ||
          (year==2025 && mon==1 && day==15) ||
          (year==2025 && mon==2 && day==12) ||
          (year==2025 && mon==3 && day==12) ||
          (year==2025 && mon==4 && day==10) ||
          (year==2025 && mon==5 && day==13) ||
          (year==2025 && mon==6 && day==11) ||
          (year==2025 && mon==7 && day==15) ||
          (year==2025 && mon==8 && day==12) ||
          (year==2025 && mon==9 && day==11) ||
          (year==2025 && mon==10 && day==24) ||
          (year==2025 && mon==12 && day==18));
  }

bool GTX_IsExactFomcDecisionDate(int year, int mon, int day)
  {
   return((year==2021 && mon==1 && day==27) ||
          (year==2021 && mon==3 && day==17) ||
          (year==2021 && mon==4 && day==28) ||
          (year==2021 && mon==6 && day==16) ||
          (year==2021 && mon==7 && day==28) ||
          (year==2021 && mon==9 && day==22) ||
          (year==2021 && mon==11 && day==3) ||
          (year==2021 && mon==12 && day==15) ||
          (year==2022 && mon==1 && day==26) ||
          (year==2022 && mon==3 && day==16) ||
          (year==2022 && mon==5 && day==4) ||
          (year==2022 && mon==6 && day==15) ||
          (year==2022 && mon==7 && day==27) ||
          (year==2022 && mon==9 && day==21) ||
          (year==2022 && mon==11 && day==2) ||
          (year==2022 && mon==12 && day==14) ||
          (year==2023 && mon==2 && day==1) ||
          (year==2023 && mon==3 && day==22) ||
          (year==2023 && mon==5 && day==3) ||
          (year==2023 && mon==6 && day==14) ||
          (year==2023 && mon==7 && day==26) ||
          (year==2023 && mon==9 && day==20) ||
          (year==2023 && mon==11 && day==1) ||
          (year==2023 && mon==12 && day==13) ||
          (year==2024 && mon==1 && day==31) ||
          (year==2024 && mon==3 && day==20) ||
          (year==2024 && mon==5 && day==1) ||
          (year==2024 && mon==6 && day==12) ||
          (year==2024 && mon==7 && day==31) ||
          (year==2024 && mon==9 && day==18) ||
          (year==2024 && mon==11 && day==7) ||
          (year==2024 && mon==12 && day==18) ||
          (year==2025 && mon==1 && day==29) ||
          (year==2025 && mon==3 && day==19) ||
          (year==2025 && mon==5 && day==7) ||
          (year==2025 && mon==6 && day==18) ||
          (year==2025 && mon==7 && day==30) ||
          (year==2025 && mon==9 && day==17) ||
          (year==2025 && mon==10 && day==29) ||
          (year==2025 && mon==12 && day==10));
  }
