// AUTO-GENERATED by scripts/economic_calendar_contract.py. DO NOT EDIT BY HAND.
#property strict

const bool GTX_ECONOMIC_CALENDAR_APPROVED = false;
const string GTX_ECONOMIC_CALENDAR_ID = "GTX-ECONOMIC-CALENDAR-DRAFT";
const string GTX_ECONOMIC_CALENDAR_SHA256 = "b4d0ebd57040aea8e4b78d205371eaebd48e16cbb50286a27c30f79d5c70866b";
const string GTX_ECONOMIC_CALENDAR_START_UTC = "2021-01-01T00:00:00Z";
const string GTX_ECONOMIC_CALENDAR_END_UTC = "2025-12-31T23:59:59Z";

bool GTX_IsExactNfpReleaseDate(int year, int mon, int day)
  {
   return false;
  }

bool GTX_IsExactCpiReleaseDate(int year, int mon, int day)
  {
   return false;
  }

bool GTX_IsExactFomcDecisionDate(int year, int mon, int day)
  {
   return false;
  }
