// AUTO-GENERATED by scripts/economic_calendar_contract.py. DO NOT EDIT BY HAND.
#property strict

const bool GTX_ECONOMIC_CALENDAR_APPROVED = false;
const string GTX_ECONOMIC_CALENDAR_ID = "GTX-ECONOMIC-CALENDAR-DRAFT";
const string GTX_ECONOMIC_CALENDAR_SHA256 = "a39c5d39fc28e6cbb44122593c2be8236a8ea92c4f48641a90882107726e896e";
const string GTX_ECONOMIC_CALENDAR_START_UTC = "2021-01-01T00:00:00Z";
const string GTX_ECONOMIC_CALENDAR_END_UTC = "2026-12-31T23:59:59Z";

bool GTX_IsExactNfpReleaseDate(int year, int mon, int day)
  {
   return false;
  }

bool GTX_IsExactCpiReleaseDate(int year, int mon, int day)
  {
   return false;
  }

bool GTX_IsExactFomcDecisionDate(int year, int mon, int day)
  {
   return false;
  }
