#!/usr/bin/env python3
"""
Golden Trade X v2.00 — FOMC Calendar Updater.

Fetches the next 12 months of FOMC meeting dates from the Federal Reserve
website (or falls back to a manually maintained hardcoded list) and outputs:
  1. A console listing of upcoming FOMC dates with countdown
  2. A ready-to-paste MQL5 IsFomcDay() code block for NewsFilter.mqh

The Fed publishes meeting calendars at:
  https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm
This script parses the HTML table as a fallback.

Usage:
    python scripts/fomc_calendar.py               # fetch + print
    python scripts/fomc_calendar.py --no-fetch    # use hardcoded list only
    python scripts/fomc_calendar.py --mql5 output/fomc_block.txt
    python scripts/fomc_calendar.py --year 2027   # show specific year

Requires (optional, for live fetch):
    pip install requests beautifulsoup4
"""

import argparse
import re
from datetime import date
from typing import List, Tuple

try:
    import requests
    from bs4 import BeautifulSoup
    _FETCH_OK = True
except ImportError:
    _FETCH_OK = False

FED_URL = "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm"

# ── Hardcoded FOMC dates (announcement day = Wednesday of meeting end) ──────────
# Format: (year, month, day) — the day the rate decision is released (19:00 UTC)
FOMC_HARDCODED: List[Tuple[int, int, int]] = [
    # 2025
    (2025, 1, 29),
    (2025, 3, 19),
    (2025, 5, 7),
    (2025, 6, 18),
    (2025, 7, 30),
    (2025, 9, 17),
    (2025, 10, 29),
    (2025, 12, 10),
    # 2026
    (2026, 1, 28),
    (2026, 3, 18),
    (2026, 4, 29),
    (2026, 6, 17),
    (2026, 7, 29),
    (2026, 9, 16),
    (2026, 10, 28),
    (2026, 12, 9),
    # 2027 (projected — verify against Fed calendar)
    (2027, 1, 27),
    (2027, 3, 17),
    (2027, 4, 28),
    (2027, 6, 16),
    (2027, 7, 28),
    (2027, 9, 15),
    (2027, 10, 27),
    (2027, 12, 8),
]

MONTH_NAMES = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


# ── Live fetch ──────────────────────────────────────────────────────────────────

def fetch_fomc_dates() -> List[Tuple[int, int, int]]:
    """Scrape FOMC announcement dates from federalreserve.gov."""
    if not _FETCH_OK:
        return []

    try:
        r = requests.get(FED_URL, timeout=15,
                         headers={"User-Agent": "GoldenTradeX-FomcCalendar/2.0"})
        r.raise_for_status()
    except Exception as e:
        print(f"  WARNING: fetch failed: {e}")
        return []

    soup = BeautifulSoup(r.text, "html.parser")
    dates: List[Tuple[int, int, int]] = []

    # Fed page uses <div class="fomc-meeting"> or similar; try multiple selectors
    # Pattern: look for text like "January 28-29, 2025" or "January 29, 2025"
    text_blocks = soup.get_text(separator="\n")
    pattern = re.compile(
        r"(January|February|March|April|May|June|July|August|September|October|November|December)"
        r"\s+(\d{1,2})(?:-\d{1,2})?,?\s+(\d{4})"
    )
    for m in pattern.finditer(text_blocks):
        month_name = m.group(1)
        day_str    = m.group(2)
        year_str   = m.group(3)
        month_num  = MONTH_NAMES.index(month_name)
        try:
            d = (int(year_str), month_num, int(day_str))
            if d not in dates and 2024 <= d[0] <= 2030:
                dates.append(d)
        except (ValueError, IndexError):
            continue

    return sorted(set(dates))


def merge_dates(fetched: List[Tuple[int, int, int]]) -> List[Tuple[int, int, int]]:
    """Merge fetched dates with hardcoded, prefer fetched for any year covered."""
    if not fetched:
        return sorted(set(FOMC_HARDCODED))

    fetched_years = set(d[0] for d in fetched)
    merged = list(fetched)
    for d in FOMC_HARDCODED:
        if d[0] not in fetched_years:
            merged.append(d)

    return sorted(set(merged))


# ── MQL5 code generation ────────────────────────────────────────────────────────

def generate_mql5_block(dates: List[Tuple[int, int, int]]) -> str:
    """Generate a ready-to-paste MQL5 IsFomcDay() function body."""
    lines = [
        "//--- FOMC Meeting Dates (auto-generated by fomc_calendar.py)",
        "//--- Paste this block inside NewsFilter.mqh > IsFomcDay(datetime t)",
        "bool IsFomcDay(datetime t)",
        "  {",
        "   MqlDateTime dt;",
        "   TimeToStruct(t, dt);",
        "   int y = dt.year, m = dt.mon, d = dt.day;",
        "",
    ]

    # Group by year
    by_year: dict = {}
    for y, mo, day in dates:
        by_year.setdefault(y, []).append((mo, day))

    for year in sorted(by_year):
        entries = by_year[year]
        lines.append(f"   if(y == {year})")
        lines.append("     {")
        conditions = " ||\n        ".join(
            f"(m == {mo} && d == {day})" for mo, day in sorted(entries)
        )
        lines.append(f"      return({conditions});")
        lines.append("     }")

    lines += [
        "",
        "   return(false);",
        "  }",
    ]
    return "\n".join(lines)


# ── Console output ──────────────────────────────────────────────────────────────

def sep(title: str = "") -> None:
    print(f"\n{'─' * 60}")
    if title:
        print(f"  {title}")
        print(f"{'─' * 60}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Golden Trade X — FOMC Calendar Updater"
    )
    parser.add_argument("--no-fetch",  action="store_true",
                        help="Skip live fetch, use hardcoded dates only")
    parser.add_argument("--year",      type=int, default=0,
                        help="Filter output to a specific year")
    parser.add_argument("--mql5",      default="",
                        help="Path to save MQL5 IsFomcDay() code block")
    args = parser.parse_args()

    sep("GOLDEN TRADE X — FOMC CALENDAR")

    if args.no_fetch or not _FETCH_OK:
        if not _FETCH_OK and not args.no_fetch:
            print("  requests/beautifulsoup4 not installed — using hardcoded dates.")
            print("  Run: pip install requests beautifulsoup4")
        dates = sorted(set(FOMC_HARDCODED))
        source = "hardcoded"
    else:
        print(f"  Fetching from {FED_URL} ...")
        fetched = fetch_fomc_dates()
        dates   = merge_dates(fetched)
        source  = f"merged (fetched {len(fetched)} + hardcoded)"

    print(f"  Source: {source}")
    print(f"  Total FOMC dates: {len(dates)}")

    today = date.today()
    filter_year = args.year

    # ── Upcoming meetings ──────────────────────────────────────────
    sep("UPCOMING FOMC MEETINGS")
    upcoming = []
    for y, mo, day in dates:
        try:
            meeting_date = date(y, mo, day)
        except ValueError:
            continue
        if filter_year and y != filter_year:
            continue
        delta = (meeting_date - today).days
        upcoming.append((meeting_date, delta))

    if not upcoming:
        print("  No meetings found for the selected filter.")
    else:
        print(f"  {'Date':<14} {'Day':<12} {'Countdown':>12}")
        for meeting_date, delta in sorted(upcoming):
            dow_name = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][meeting_date.weekday()]
            if delta < 0:
                countdown = f"{-delta} days ago"
            elif delta == 0:
                countdown = "TODAY"
            elif delta <= 7:
                countdown = f"in {delta} days (!)"
            else:
                countdown = f"in {delta} days"
            print(f"  {str(meeting_date):<14} {dow_name:<12} {countdown:>12}")

    # ── Next meeting alert ─────────────────────────────────────────
    future = [(d, delta) for d, delta in upcoming if delta >= 0]
    if future:
        next_date, next_delta = min(future, key=lambda x: x[1])
        sep("NEXT FOMC")
        print(f"  Date:    {next_date}")
        print(f"  In:      {next_delta} day(s)")
        print(f"  Buffer:  block trading {next_delta - 1} day(s) before (InpNewsBufferBefore)")
        if next_delta <= 3:
            print("  *** IMMINENT — consider activating InpPauseForNews=true ***")

    # ── MQL5 block generation ──────────────────────────────────────
    mql5_block = generate_mql5_block(dates)

    sep("MQL5 IsFomcDay() CODE BLOCK")
    print(mql5_block)

    if args.mql5:
        with open(args.mql5, "w", encoding="utf-8") as f:
            f.write(mql5_block + "\n")
        print(f"\n  MQL5 block saved → {args.mql5}")

    # ── Summary by year ────────────────────────────────────────────
    sep("MEETINGS BY YEAR")
    by_year: dict = {}
    for y, mo, day in dates:
        by_year.setdefault(y, 0)
        by_year[y] += 1
    for y in sorted(by_year):
        print(f"  {y}: {by_year[y]} meetings")


if __name__ == "__main__":
    main()
