#!/usr/bin/env python3
"""
Golden Trade X — FOMC Calendar Updater.

Fetches FOMC meeting dates from the Federal Reserve website (or falls back to
a manually maintained verified list) and outputs a console listing plus a
ready-to-paste MQL5 IsFomcDecisionDate() block.

The Fed publishes meeting calendars at:
  https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm

Usage:
    python scripts/fomc_calendar.py
    python scripts/fomc_calendar.py --no-fetch
    python scripts/fomc_calendar.py --mql5 output/fomc_block.txt
    python scripts/fomc_calendar.py --year 2027
"""

import argparse
import re
from datetime import date
from typing import List, Tuple

try:
    import requests
    from bs4 import BeautifulSoup
    _FETCH_OK = True
except ImportError:
    _FETCH_OK = False

FED_URL = "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm"

# Decision/statement dates verified against the Federal Reserve calendar.
FOMC_HARDCODED: List[Tuple[int, int, int]] = [
    # 2025
    (2025, 1, 29), (2025, 3, 19), (2025, 5, 7), (2025, 6, 18),
    (2025, 7, 30), (2025, 9, 17), (2025, 10, 29), (2025, 12, 10),
    # 2026
    (2026, 1, 28), (2026, 3, 18), (2026, 4, 29), (2026, 6, 17),
    (2026, 7, 29), (2026, 9, 16), (2026, 10, 28), (2026, 12, 9),
    # 2027 published calendar
    (2027, 1, 27), (2027, 3, 17), (2027, 4, 28), (2027, 6, 9),
    (2027, 7, 28), (2027, 9, 15), (2027, 10, 27), (2027, 12, 8),
]

MONTH_NAMES = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


def fetch_fomc_dates() -> List[Tuple[int, int, int]]:
    """Scrape FOMC announcement dates from federalreserve.gov."""
    if not _FETCH_OK:
        return []
    try:
        r = requests.get(
            FED_URL,
            timeout=15,
            headers={"User-Agent": "GoldenTradeX-FomcCalendar/3.0"},
        )
        r.raise_for_status()
    except Exception as exc:
        print(f"  WARNING: fetch failed: {exc}")
        return []

    soup = BeautifulSoup(r.text, "html.parser")
    dates: List[Tuple[int, int, int]] = []
    text_blocks = soup.get_text(separator="\n")
    pattern = re.compile(
        r"(January|February|March|April|May|June|July|August|September|October|November|December)"
        r"\s+(\d{1,2})(?:-\d{1,2})?,?\s+(\d{4})"
    )
    for match in pattern.finditer(text_blocks):
        month_name = match.group(1)
        day_str = match.group(2)
        year_str = match.group(3)
        month_num = MONTH_NAMES.index(month_name)
        try:
            value = (int(year_str), month_num, int(day_str))
            if value not in dates and 2024 <= value[0] <= 2030:
                dates.append(value)
        except (ValueError, IndexError):
            continue
    return sorted(set(dates))


def merge_dates(fetched: List[Tuple[int, int, int]]) -> List[Tuple[int, int, int]]:
    """Merge fetched dates with hardcoded values, preferring fetched years."""
    if not fetched:
        return sorted(set(FOMC_HARDCODED))
    fetched_years = {row[0] for row in fetched}
    merged = list(fetched)
    for row in FOMC_HARDCODED:
        if row[0] not in fetched_years:
            merged.append(row)
    return sorted(set(merged))


def generate_mql5_block(dates: List[Tuple[int, int, int]]) -> str:
    """Generate a block matching NewsFilter.mqh IsFomcDecisionDate()."""
    lines = [
        "//--- FOMC decision dates (auto-generated by fomc_calendar.py)",
        "bool IsFomcDecisionDate(int year, int mon, int day)",
        "  {",
    ]
    by_year: dict[int, list[tuple[int, int]]] = {}
    for year, month, day in dates:
        by_year.setdefault(year, []).append((month, day))
    for year in sorted(by_year):
        conditions = " ||\n             ".join(
            f"(mon=={month} && day=={day})" for month, day in sorted(by_year[year])
        )
        lines.append(f"   if(year == {year})")
        lines.append(f"      return({conditions});")
    lines += ["   return(false);", "  }"]
    return "\n".join(lines)


def sep(title: str = "") -> None:
    print(f"\n{'─' * 60}")
    if title:
        print(f"  {title}")
        print(f"{'─' * 60}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Golden Trade X — FOMC Calendar Updater")
    parser.add_argument("--no-fetch", action="store_true", help="Skip live fetch")
    parser.add_argument("--year", type=int, default=0, help="Filter output to a year")
    parser.add_argument("--mql5", default="", help="Save generated MQL5 block")
    args = parser.parse_args()

    sep("GOLDEN TRADE X — FOMC CALENDAR")
    if args.no_fetch or not _FETCH_OK:
        dates = sorted(set(FOMC_HARDCODED))
        source = "verified hardcoded fallback"
    else:
        print(f"  Fetching from {FED_URL} ...")
        fetched = fetch_fomc_dates()
        dates = merge_dates(fetched)
        source = f"merged (fetched {len(fetched)} + verified fallback)"
    print(f"  Source: {source}")
    print(f"  Total FOMC dates: {len(dates)}")

    today = date.today()
    sep("FOMC MEETINGS")
    upcoming = []
    for year, month, day in dates:
        if args.year and year != args.year:
            continue
        meeting = date(year, month, day)
        upcoming.append((meeting, (meeting - today).days))
    for meeting, delta in sorted(upcoming):
        print(f"  {meeting}  delta_days={delta}")

    mql5_block = generate_mql5_block(dates)
    sep("MQL5 IsFomcDecisionDate() CODE BLOCK")
    print(mql5_block)
    if args.mql5:
        with open(args.mql5, "w", encoding="utf-8") as handle:
            handle.write(mql5_block + "\n")
        print(f"\n  MQL5 block saved → {args.mql5}")


if __name__ == "__main__":
    main()
